# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Install GCC and Make"
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc make

      - run:
          name: Build calendar exe
          command: make